In [1]:
import numpy as np

In [4]:
a1= np.array ([[1, 2, 3, 3, 1],[6, 8, 11, 10, 7]])
a1

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [7]:
a=a1.T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [14]:
mean_a=a.mean(axis=0)
mean_a

array([2. , 8.4])

In [15]:
a_centered= a-mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [20]:
a_centered_sp=a_centered[:,0]@a_centered[:,1]
a_centered_sp

8.0

In [21]:
a_centered_sp=a_centered_sp/ (len(a_centered)-1)
a_centered_sp

2.0

In [22]:
np.cov=np.cov(m=a.T)[0,1]
np.cov

2.0

In [23]:
np.cov==a_centered_sp

True